### ISSUE TITLE
Linux gcc error: unrecognized command line option '-m64'

### ISSUE THREAD

**Issue by TurBoss** [GIPdA/ArduinoQbs#1]
hello, 

I'm trying to build a teensy project bun when I run compile/build i get this error

```
/home/turboss/Qt/Tools/QtCreator/share/qtcreator/qbs/share/qbs/imports/qbs/Probes/GccProbe.qbs:57: warning: Error: Process '/home/turboss/PortableApps/arduino-1.8.5/hardware/tools/arm/bin/arm-none-eabi-gcc' finished with exit code 1. The standard error output was:
arm-none-eabi-gcc: error: unrecognized command line option '-m64'
```

also no such file upload.sh, can't fin is in the project

Thank you

**Comment by GIPdA** [comment]
Hi,
Which version of QBS are you using? Latest working version was QBS 1.7 or 1.8 I think, up to commit 86a75bd8.
The QBS API isn't stable yet, and each new release was breaking something so I decided to wait before going further. I didn't had the time to really keep up but I hope to get back to it soon.

Latest commit isn't working with any version, I was working on a new way to choose a board and fill build options (from Arduino boards file), but it's not finished and may not work anymore with QBS 1.11 due to API changes.

**Comment by TurBoss** [comment]
I was trying to use master branch, I'll downgrade to 1.7 or 1.8

lets see if works


thank you

**Comment by GIPdA** [comment]
You might want to try the latest commit, I can compile successfully for Teensy and AVR with it. Using QtC 4.6.0 and Qbs 1.11.0 (and Arduino 1.8.4).
Upload isn't working yet though. But for Teensy you can use TeensyLoader directly or run the generated upload.sh script manually.

And about your first error, your kit/compiler setup may be wrong? I don't know where from the -m64 option comes, but I also never tested the project under Linux. You may want to check Qbs profiles settings (QtC preferences).

**Comment by TurBoss** [comment]
ok,

 sadly my hdd died and now I'm on windows
I'll try to get the same setup asap

I'm testing on windows

**Comment by TurBoss** [comment]
hello,
until i get my sistem up again I can close
